package job

const JOB_TYPE_IMPORT_USERS = "IMPORT_USERS"

const JOB_STATUS_PENDING = "PENDING"
const JOB_STATUS_PROCESSING = "PROCESSING"
const JOB_STATUS_DONE = "DONE"

var JOB_STATUS map[string]string = map[string]string{
	JOB_STATUS_PENDING:    JOB_STATUS_PENDING,
	JOB_STATUS_PROCESSING: JOB_STATUS_PROCESSING,
	JOB_STATUS_DONE:       JOB_STATUS_DONE,
}
