host: ""
port: 8080
database: 
  host: "0.0.0.0"
  port: 27017
  username: ""
  password: ""
  dbname: "codev"
  sslmode: "disable"
directory:
  import_users: "<upload directory for csv files - import users>"
  mail_templates: <email templates directory>"
mail:
  from: "...@gmail.com"
  smtp_host: "smtp.mailtrap.io"
  smtp_port: "2525"
  smtp_user : "282889e9032f1d"
  smtp_pwd: "4266ee3ef4db6d"
log:
  log_dir: "<log directory>"